###
POST http://localhost:3333/v1/usuario
Content-Type: application/json

{
  "nome": "Usuario Teste",
  "sobrenome": "Sobrenome Teste",
  "email": "teste@teste.com",
  "senha": "123456"
}

### RETORNA TODOS OS USUÁRIOS
GET http://localhost:3333/v1/usuario

### RETORNA O USUÁRIO PELO ID
GET http://localhost:3333/v1/usuario/1

### ATUALIZA O USUÁRIO PELO ID
PATCH  http://localhost:3333/v1/usuario/1
Content-Type: application/json

{
  "nome": "Leonardo",
  "sobrenome": "Muhlenhoff Rocha"
}

### DELETA O USUÁRIO PELO ID
DELETE http://localhost:3333/v1/usuario/2